//created on: 28.05.2015
package beimi.room
//list any import classes here.
import com.beimi.web.model.GameRoom
dialect  "mvel"

//declare any global variables here


rule "createroom_dizhu"
	salience 100
	lock-on-active true
    when
        $gameRoom:GameRoom(extparams!= null , extparams.get("gametype") == "dizhu")
    then
        modify($gameRoom) {numofgames = $gameRoom.extparams["games"] };
end

rule "createroom_dezhou"
	salience 100
	lock-on-active true
    when
        $gameRoom:GameRoom(extparams!= null , extparams.get("gametype") == "dezhou")
    then
        modify($gameRoom) {numofgames = $gameRoom.extparams["games"] };
end

rule "createroom_bullfight"
	salience 100
	lock-on-active true
    when
        $gameRoom:GameRoom(extparams!= null , extparams.get("gametype") == "bullfight")
    then
        modify($gameRoom) {numofgames = $gameRoom.extparams["games"] };
end

rule "createroom_zhajinhua"
	salience 100
	lock-on-active true
    when
        $gameRoom:GameRoom(extparams!= null , extparams.get("gametype") == "zhajinhua")
    then
        modify($gameRoom) {numofgames = $gameRoom.extparams["games"] };
end